using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GSAV.Data.Common
{
    public class SP
    {
       
        public static string SP_VALIDARACCESO = "SP_VALIDARACCESO";
        public static string GSAV_SP_VALIDARACCESO = "GSAV.SP_VALIDARACCESO";
        public static string GSAV_SP_CONSULTAR_SOLICITUDES = "GSAV.SP_CONSULTAR_SOLICITUDES";
        public static string GSAV_SP_OBTENER_SOLICITUD = "GSAV.GSAV.SP_OBTENER_SOLICITUD";
        public static string GSAV_SP_UPD_SOLUCION_CONSULTA = "GSAV.SP_UPD_SOLUCION_CONSULTA";
        public static string GSAV_SP_CONSULTAR_SOLICITUDES_DSH = "GSAV.SP_CONSULTAR_SOLICITUDES_DSH";
        public static string GSAV_SP_CONSULTAR_DEMANDA_UNID_NEG = "GSAV.SP_CONSULTAR_DEMANDA_UNID_NEG";
        public static string GSAV_SP_CONSULTAR_DEMANDA_INTENCION = "GSAV.SP_CONSULTAR_DEMANDA_INTENCION";
        public static string GSAV_SP_BUSCAR_FECHA_CREA_INTENCION = "GSAV.SP_BUSCAR_FECHA_CREA_INTENCION";
        public static string GSAV_SP_BUSCAR_INTENCIONES = "GSAV.SP_BUSCAR_INTENCIONES";
        public static string GSAV_SP_INSERTAR_INTENCION_CONSULTA = "GSAV.SP_INSERTAR_INTENCION_CONSULTA";
        public static string GSAV_SP_BUSCAR_INTENCION_X_NOMBRE = "GSAV.SP_BUSCAR_INTENCION_X_NOMBRE";
        public static string GSAV_SP_ELIMINAR_INTENCION_X_ID_DIALOG_FLOW = "GSAV.SP_ELIMINAR_INTENCION_X_ID_DIALOG_FLOW";
        public static string GSAV_SP_CONSULTAR_SOLICITUDES_PENDIENTES_ALERTA = "GSAV.SP_CONSULTAR_SOLICITUDES_PENDIENTES_ALERTA";
        public static string GSAV_SP_UPD_FECHA_NOTIFICACION_SOLICITUD = "GSAV.SP_UPD_FECHA_NOTIFICACION_SOLICITUD";
    }
}
